=== Herdo/strongtypes/src/DotNetStandard/StrongTypes/StrongTypesConfiguration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="strongTypes" targetNamespace="https://www.github.com/Herdo/strongtypes" xmlns:mstns="https://www.github.com/Herdo/strongtypes" xmlns="https://www.github.com/Herdo/strongtypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:simpleType name="allowedBaseType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="System.Boolean" />
      <xs:enumeration value="System.Byte" />
      <xs:enumeration value="System.DateTime" />
      <xs:enumeration value="System.DateTimeOffset" />
      <xs:enumeration value="System.Decimal" />
      <xs:enumeration value="System.Double" />
      <xs:enumeration value="System.Guid" />
      <xs:enumeration value="System.Int16" />
      <xs:enumeration value="System.Int32" />
      <xs:enumeration value="System.Int64" />
      <xs:enumeration value="System.SByte" />
      <xs:enumeration value="System.Single" />
      <xs:enumeration value="System.String" />
      <xs:enumeration value="System.UInt16" />
      <xs:enumeration value="System.UInt32" />
      <xs:enumeration value="System.UInt64" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="strongTypes" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="strongType">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="validate" type="xs:string" minOccurs="0" msdata:Ordinal="0" />
              <xs:element name="formatString" type="xs:string" minOccurs="0" msdata:Ordinal="1" />
              <xs:element name="customDescription" type="xs:string" minOccurs="0" msdata:Ordinal="2" />
              <xs:element name="excludeOperator" type="xs:string" minOccurs="0" maxOccurs="unbounded" msdata:Ordinal="2" />
            </xs:sequence>
            <xs:attribute name="name" use="required" form="unqualified" type="xs:string" />
            <xs:attribute name="internalType" use="required" form="unqualified" type="allowedBaseType" />
            <xs:attribute name="provideNewtonsoftJsonConverter" form="unqualified" type="xs:boolean" />
            <xs:attribute name="provideSystemTextJsonConverter" form="unqualified" type="xs:boolean" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Herdo/strongtypes/src/DotNetStandard/StrongTypes/StrongTypesConfiguration.xml
<?xml version="1.0" encoding="utf-8" ?>
<strongTypes xmlns="https://www.github.com/Herdo/strongtypes"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://www.github.com/Herdo/strongtypes StrongTypesConfiguration.xsd">
  <strongType name="UserID" internalType="System.Int32"/>
  <strongType name="CustomerID" internalType="System.Int32">
    <formatString>D5</formatString>
    <customDescription><![CDATA[CustomerID with consistent formatting across all applications.]]></customDescription>
    <excludeOperator>Add</excludeOperator>
    <excludeOperator>Subtract</excludeOperator>
    <!-- We don't re-use customer IDs, so there's no need to decrement -->
    <excludeOperator>Decrement</excludeOperator>
    <!-- None of our customer IDs is "more" or "less" than the other - we don't need to compare them this way -->
    <excludeOperator>LessThan</excludeOperator>
    <excludeOperator>GreaterThan</excludeOperator>
    <excludeOperator>LessThanOrEqual</excludeOperator>
    <excludeOperator>GreaterThanOrEqual</excludeOperator>
  </strongType>
  <strongType name="Year" internalType="System.Int16">
    <validate>true</validate>
    <excludeOperator>Add</excludeOperator>
    <excludeOperator>Substract</excludeOperator>
  </strongType>
  <strongType name="Years" internalType="System.Int16"/>
</strongTypes>
